#!/bin/sh /etc/rc.common

START=90
STOP=15

PID_FILE='/var/run/sysuh3c.pid'

get_config() {
	config_get_bool enable $1 enable
	config_get username $1 username
	config_get password $1 password
}

start() {
	[ "$enable" = 1 ] || exit 0

	ifname=$(uci -q get network.wan.ifname)
	[ -n "$ifname" ] || exit 1

	/usr/bin/sysuh3c -i $ifname -u $username -p $password -d
	return $?
}

stop() {
	kill $(cat $PID_FILE) > /dev/null 2>&1
	rm -rf $PID_FILE
}
